<?php
require_once __DIR__ . "/strings.php";

const ERR_DB_EXCEPTION = 100;
const ERR_CREATE_FOLDER = 200;
const ERR_BROKEN_REQUEST_CLASS = 300;
const ERR_AUTH_REQUIRED = 403;
const ERR_UNKNOWN_ACTION = 999;
const ERR_UNKNOWN = 1000;
const ERR_SECURITY_FAILED = 1101;
const ERR_WRONG_PASSWORD = 1102;

const ERR_EMPTY_NAME = 1;
const ERR_EMPTY_EMAIL = 2;
const ERR_EMPTY_PASSWORD = 3;
const ERR_INVALID_EMAIL = 4;
const ERR_EXISTING_EMAIL = 5;
const ERR_AUTH_FAILED = 6;
const ERR_INVALID_YANDEX_RESPONSE = 7;
const ERR_EMPTY_TITLE = 8;
const ERR_EMPTY_TEXT = 9;


const ERRORS = [
    ERR_UNKNOWN_ACTION              => [KEY_USER_MESSAGE => STR_ERR_UNKNOWN_ACTION],
    ERR_AUTH_REQUIRED               => [KEY_USER_MESSAGE => STR_ERR_AUTH_REQUIRED],
    ERR_AUTH_FAILED                 => [KEY_USER_MESSAGE => STR_ERR_AUTH_FAILED],
    ERR_UNKNOWN                     => [KEY_USER_MESSAGE => STR_ERR_UNKNOWN, KEY_IS_RECOVERABLE=>1],
    ERR_EMPTY_NAME                  => [KEY_USER_MESSAGE => STR_ERR_EMPTY_NAME],
    ERR_EMPTY_EMAIL                 => [KEY_USER_MESSAGE => STR_ERR_EMPTY_EMAIL],
    ERR_EMPTY_PASSWORD              => [KEY_USER_MESSAGE => STR_ERR_EMPTY_PASSWORD],
    ERR_INVALID_EMAIL               => [KEY_USER_MESSAGE => STR_ERR_INVALID_EMAIL],
    ERR_EXISTING_EMAIL              => [KEY_USER_MESSAGE => STR_ERR_EXISTING_EMAIL],
    ERR_INVALID_YANDEX_RESPONSE     => [KEY_USER_MESSAGE => STR_ERR_INVALID_YANDEX_RESPONSE],
    ERR_EMPTY_TITLE                 => [KEY_USER_MESSAGE => STR_ERR_EMPTY_TITLE],
    ERR_EMPTY_TEXT                  => [KEY_USER_MESSAGE => STR_ERR_EMPTY_TITLE],
];
